package io.neuralheads.kmpworker.persistence

import io.neuralheads.kmpworker.core.Constraints
import io.neuralheads.kmpworker.core.RetryPolicy
import io.neuralheads.kmpworker.core.TaskRequest
import io.neuralheads.kmpworker.core.TaskType
import io.neuralheads.kmpworker.persistence.db.KmpWorkerDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.withContext

/**
 * SQLDelight-backed implementation of [TaskRepository].
 *
 * All DB operations are dispatched to [Dispatchers.IO] to avoid blocking
 * the main thread.
 *
 * The [Tasks] data class is generated by SQLDelight in the same package
 * (`io.neuralheads.kmpworker.persistence`), not in the `.db` sub-package.
 *
 * @param database The SQLDelight generated database instance.
 */
class SqlDelightTaskRepository(
    private val database: KmpWorkerDatabase
) : TaskRepository {

    private val queries get() = database.tasksQueries

    override suspend fun insert(task: TaskRequest): Unit = withContext(Dispatchers.IO) {
        queries.insertTask(
            id        = task.id,
            type      = task.type.toDbString(),
            status    = "PENDING",
            retry_count = 0L,
            payload   = task.payload,
            created_at = currentEpochMillis()
        )
    }

    override suspend fun updateStatus(
        id: String,
        status: String,
        retryCount: Int
    ): Unit = withContext(Dispatchers.IO) {
        queries.updateStatus(
            status      = status,
            retry_count = retryCount.toLong(),
            id          = id
        )
    }

    override suspend fun delete(id: String): Unit = withContext(Dispatchers.IO) {
        queries.deleteTask(id)
    }

    override suspend fun getAll(): List<TaskRequest> = withContext(Dispatchers.IO) {
        queries.getAll(::mapRow).executeAsList().map { it.toTaskRequest() }
    }

    override suspend fun getPending(): List<TaskRequest> = withContext(Dispatchers.IO) {
        queries.getPending(::mapRow).executeAsList().map { it.toTaskRequest() }
    }

    override suspend fun getById(id: String): TaskRequest? = withContext(Dispatchers.IO) {
        queries.getById(id, ::mapRow).executeAsOneOrNull()?.toTaskRequest()
    }

    // ── Mapping helpers ──────────────────────────────────────────────────────

    /**
     * Column mapper for SQLDelight query results.
     * [Tasks] is generated in the `io.neuralheads.kmpworker.persistence` package.
     */
    private fun mapRow(
        id: String,
        type: String,
        status: String,
        retry_count: Long,
        payload: String?,
        created_at: Long
    ): Tasks = Tasks(id, type, status, retry_count, payload, created_at)

    private fun Tasks.toTaskRequest(): TaskRequest = TaskRequest(
        id      = id,
        type    = type.toTaskType(),
        payload = payload
    )

    private fun TaskType.toDbString(): String = when (this) {
        is TaskType.OneTime  -> "OneTime"
        is TaskType.Periodic -> "Periodic:${repeatIntervalMillis}"
    }

    private fun String.toTaskType(): TaskType {
        return if (this == "OneTime") {
            TaskType.OneTime
        } else {
            val interval = removePrefix("Periodic:").toLongOrNull() ?: 0L
            TaskType.Periodic(repeatIntervalMillis = interval)
        }
    }
}

/**
 * Returns the current time as Unix epoch milliseconds.
 * Implemented via expect/actual per platform.
 */
internal expect fun currentEpochMillis(): Long
